from lumiweb.strip import Strip
import neopixel
import board

GARAGE_START = 0 
GARAGE_END = 199
LIVING_ROOM_START = 200
LIVING_ROOM_END = 333
PITCH_START = 334
PITCH_PEAK = 378 
PITCH_END = 423
# 424 OFFICE_START
# 582 OFFICE_END
# 583 SIDE_START
# 721 SIDE END
NUM_PIXELS = 424
GPIO_PIN = board.D18

STRIP = Strip(GPIO_PIN, NUM_PIXELS, pixel_order=neopixel.GRB)